export const MyData=[
  
    {
        id:1,
        name:'Chocolate Cake',
        images:"https://images.unsplash.com/photo-1605807646983-377bc5a76493?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTB8fGNob2NvbGF0ZSUyMGNha2V8ZW58MHx8MHx8&w=1000&q=80",
        image1:"https://img.freepik.com/free-photo/chocolate-cake-with-dried-fruit_144627-9029.jpg?w=2000",
        description:"This is a classic cake made with cocoa powder, all-purpose flour, granulated sugar, baking powder, baking soda, salt, milk, vegetable oil, eggs, and vanilla extract. It can be served plain or with frosting.",
        description1: "Ingredients:<br>For the cake:<br>2 cups all-purpose flour<br>2 cups granulated sugar<br>3/4 cup unsweetened cocoa powder<br>2 teaspoons baking powder<br>1 1/2 teaspoons baking soda<br>1 teaspoon salt<br>1 cup milk<br>1/2 cup vegetable oil<br>2 large eggs<br>2 teaspoons vanilla extract<br>1 cup hot water<br><br>For the frosting:<br>1 cup unsalted butter, softened<br>3 1/2 cups powdered sugar<br>1/2 cup unsweetened cocoa powder<br>1/2 cup milk<br>2 teaspoons vanilla extract<br><br>Instructions:<br><br>Preheat your oven to 350°F (175°C). Grease two 9-inch cake pans with cooking spray or butter.<br>In a large mixing bowl, whisk together the flour, sugar, cocoa powder, baking powder, baking soda, and salt.<br>Add the milk, vegetable oil, eggs, and vanilla extract to the dry ingredients and beat with an electric mixer on medium speed until well combined.<br>Gradually pour in the hot water while beating on low speed. Mix until just combined.<br>Divide the batter evenly between the two prepared cake pans and smooth the tops with a spatula.<br>Bake the cakes for 30-35 minutes, or until a toothpick inserted into the center of the cake comes out clean.<br>Let the cakes cool in the pans for 10 minutes, then remove them from the pans and cool completely on a wire rack.<br>To make the frosting, beat the butter with an electric mixer on medium speed until smooth.<br>Gradually add the powdered sugar and cocoa powder, beating on low speed until well combined.<br>Add the milk and vanilla extract, and beat on high speed until the frosting is light and fluffy.<br>Frost the top of one cake layer with a thick layer of frosting. Place the second cake layer on top and frost the top and sides of the cake with the remaining frosting.<br>Decorate as desired and serve your delicious chocolate cake!",
        price:25,
        },
        {
            id: 2,
            name: "Vanilla Cake",
            images: "https://d3cif2hu95s88v.cloudfront.net/live-site-2016/product-image/IMG/15786649727-350x350.jpg",
            description:"It actually just refers to the flavor of a vanilla custard (aka the classic French way of making ice cream from cream and egg yolks). French vanilla cake mimics a custard flavor by including egg yolks in the batter, making it a yellow cake",
            image1:"https://assets.bonappetit.com/photos/605e3f77bc9004a6f43165aa/16:9/w_3488,h_1962,c_limit/Basically-Vanilla-Cake-01.jpg",
            description1: "Ingredients:<br>- 2 and 1/2 cups (312g) all-purpose flour<br>- 2 and 1/2 teaspoons baking powder<br>- 1 teaspoon salt<br>- 1 cup (2 sticks or 226g) unsalted butter, softened to room temperature<br>- 1 and 3/4 cups (350g) granulated sugar<br>- 4 large eggs, at room temperature<br>- 2 teaspoons pure vanilla extract<br>- 1 and 1/2 cups (360ml) whole milk, at room temperature<br><br>Instructions:<br>1. Preheat your oven to 350°F (180°C). Grease two 9-inch (23cm) round cake pans and line the bottoms with parchment paper.<br>2. In a medium-sized bowl, whisk together the flour, baking powder, and salt.<br>3. In a large bowl, beat the butter and sugar together on medium speed until creamy and smooth, about 3-4 minutes.<br>4. Add the eggs one at a time, beating well after each addition. Then add the vanilla extract and mix until combined.<br>5. Gradually add the dry ingredients to the wet ingredients in three parts, alternating with the milk. Begin and end with the dry ingredients. Mix each addition until just combined, being careful not to overmix the batter.<br>6. Divide the batter evenly between the two prepared cake pans.<br>7. Bake for 25-30 minutes, or until a toothpick inserted into the center of the cakes comes out clean.<br>8. Allow the cakes to cool in the pans for 10 minutes, then remove them from the pans and place them on a wire rack to cool completely.<br>9. Once the cakes have cooled completely, you can frost and decorate them as desired. Enjoy your delicious vanilla cake!",
            price:50
            },
    {
        id:3,
        name:'Red Velvet',
        images: 'https://media.istockphoto.com/id/1344684639/photo/delicious-homemade-red-velvet-cake.jpg?b=1&s=170667a&w=0&k=20&c=EHzRzBKhLOrImw0DOpnBmCBci6figZqqAm3HUyXl5Yc=',
        image1:"https://www.naturallysweetkitchen.com/wp-content/uploads/2021/02/natural-red-velvet-cake-ggl.jpg",
        description:"This is a popular cake that has a unique red color, often made with cocoa powder, vinegar, and buttermilk.",
        description1: "Ingredients:<br>- 2 and 1/2 cups (312g) all-purpose flour<br>- 1 and 1/2 cups (300g) granulated sugar<br>- 1 teaspoon baking powder<br>- 1 teaspoon baking soda<br>- 1 teaspoon salt<br>- 1 teaspoon cocoa powder<br>- 1 and 1/2 cups (360ml) vegetable oil<br>- 1 cup (240ml) buttermilk, at room temperature<br>- 2 large eggs, at room temperature<br>- 1 oz. (28g) red food coloring (liquid or gel)<br>- 2 teaspoons vanilla extract<br>- 1 teaspoon white vinegar<br><br>For the Cream Cheese Frosting:<br>- 1 cup (2 sticks or 226g) unsalted butter, softened to room temperature<br>- 16 oz. (452g) cream cheese, softened to room temperature<br>- 6 cups (720g) powdered sugar<br>- 2 teaspoons vanilla extract<br><br>Instructions:<br>1. Preheat your oven to 350°F (180°C). Grease two 9-inch (23cm) round cake pans and line the bottoms with parchment paper.<br>2. In a medium-sized bowl, whisk together the flour, sugar, baking powder, baking soda, salt, and cocoa powder.<br>3. In a large bowl, whisk together the vegetable oil, buttermilk, eggs, red food coloring, vanilla extract, and white vinegar until well combined.<br>4. Gradually add the dry ingredients to the wet ingredients in three parts, mixing until just combined after each addition.<br>5. Divide the batter evenly between the two prepared cake pans.<br>6. Bake for 25-30 minutes, or until a toothpick inserted into the center of the cakes comes out clean.<br>7. Allow the cakes to cool in the pans for 10 minutes, then remove them from the pans and place them on a wire rack to cool completely.<br>8. To make the cream cheese frosting, beat the butter and cream cheese together on medium speed until smooth and creamy, about 2-3 minutes.<br>9. Gradually add the powdered sugar and vanilla extract, and beat on low speed until just combined. Then increase the speed to high and beat until the frosting is light and fluffy.<br>10. Once the cakes have cooled completely, spread a layer of frosting over one cake, then place the second cake on top. Spread frosting over the top and sides of the cake.<br>11. Enjoy your delicious red velvet cake!",
        price:50
   

    },
    {
        id:4,
        name:'Carrot Cake',
        images: 'https://media.istockphoto.com/id/1170788512/photo/slice-of-homemade-carrot-cake-with-cream-cheese-frosting-side-view-table-scene-against-white.jpg?s=612x612&w=0&k=20&c=0MisjjRRS9OG1qN1FqwXNnoZfJYkab56u8mZblR06AY=',
        image1:"https://www.abeautifulplate.com/wp-content/uploads/2019/04/carrot-cake-with-pineapple-and-coconut-1-3-500x500.jpg",
        description:"This cake is made with grated carrots, which add moisture and flavor. It is often topped with a cream cheese frosting",
        description1: "Ingredients:<br>- 2 cups (250g) all-purpose flour<br>- 2 tsp baking powder<br>- 1 1/2 tsp baking soda<br>- 1 tsp salt<br>- 2 tsp ground cinnamon<br>- 1/2 tsp ground ginger<br>- 1/4 tsp ground nutmeg<br>- 1/4 tsp ground cloves<br>- 1 1/2 cups (300g) granulated sugar<br>- 1 cup (240ml) vegetable oil<br>- 3 large eggs<br>- 1 tsp vanilla extract<br>- 2 cups (200g) grated carrots<br><br>For the cream cheese frosting:<br>- 1/2 cup (1 stick) unsalted butter, at room temperature<br>- 8 oz (226g) cream cheese, at room temperature<br>- 4 cups (500g) powdered sugar<br>- 1 tsp vanilla extract<br><br>Instructions:<br>1. Preheat the oven to 350°F (180°C). Grease two 9-inch (23cm) round cake pans and line the bottoms with parchment paper.<br>2. In a medium bowl, whisk together the flour, baking powder, baking soda, salt, cinnamon, ginger, nutmeg, and cloves.<br>3. In a large bowl, whisk together the sugar, oil, eggs, and vanilla extract. Add the dry ingredients to the wet ingredients and stir until just combined. Fold in the grated carrots.<br>4. Divide the batter evenly between the prepared pans and bake for 30-35 minutes, or until a toothpick inserted into the center of the cakes comes out clean. Let the cakes cool in the pans for 10 minutes, then remove them from the pans and place them on a wire rack to cool completely.<br>5. To make the cream cheese frosting, beat the butter and cream cheese with an electric mixer until creamy. Add the powdered sugar and vanilla extract and beat until smooth and fluffy.<br>6. Once the cakes have cooled completely, spread a layer of frosting over one cake, then place the second cake on top. Spread frosting over the top and sides of the cake. Enjoy your delicious Carrot Cake!",
        price:45

    },
    {
        id:5,
        name:'Cheesecake',
        images: 'https://media.istockphoto.com/id/1205169550/photo/cheesecake-slice-with-strawberries.jpg?s=612x612&w=0&k=20&c=Vr9g9CMxNQuHDlMwjgOiUxQtABSAp8KeYR7bfUZpeMs=',
        image1:"https://images.unsplash.com/photo-1524351199678-941a58a3df50?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mnx8Y2hlZXNlY2FrZXxlbnwwfHwwfHw%3D&w=1000&q=80",
        description:"This is a dense, creamy cake made with cream cheese, eggs, and sugar. It can be served plain or with fruit or chocolate toppings.",
        description1: "Ingredients:<br>- 2 cups graham cracker crumbs<br>- 1/2 cup unsalted butter, melted<br>- 1/4 cup granulated sugar<br>- 4 (8 oz) packages cream cheese, softened<br>- 1 1/4 cups granulated sugar<br>- 1 tsp vanilla extract<br>- 4 large eggs<br>- 1/3 cup sour cream<br><br>Instructions:<br>1. Preheat the oven to 350°F (175°C).<br>2. Mix the graham cracker crumbs, melted butter, and 1/4 cup of granulated sugar in a bowl.<br>3. Press the mixture into the bottom of a 9-inch springform pan.<br>4. In a large bowl, beat the cream cheese, 1 1/4 cups granulated sugar, and vanilla extract together until smooth.<br>5. Beat in the eggs, one at a time.<br>6. Stir in the sour cream.<br>7. Pour the mixture into the prepared crust.<br>8. Bake for 45 to 50 minutes or until the cheesecake is set but still jiggles slightly in the center.<br>9. Let the cheesecake cool completely in the pan.<br>10. Chill the cheesecake in the refrigerator for at least 4 hours or overnight before serving.",
        price:45

       
    },
    {
        id:6,
        name:'Pound Cake',
        images: 'https://t3.ftcdn.net/jpg/01/91/48/38/360_F_191483809_HbX64RQmet3CzorqR5TZEQSnRmjNNUBV.jpg',
        image1:"https://images.unsplash.com/photo-1534353875273-b5887cc1abf5?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mnx8cG91bmQlMjBjYWtlfGVufDB8fDB8fA%3D%3D&w=1000&q=80",
        description:"This is a dense, buttery cake made with a pound each of butter, sugar, eggs, and flour.",
        description1: "Ingredients:<br>- 1 pound (4 sticks) unsalted butter, at room temperature<br>- 3 cups granulated sugar<br>- 6 large eggs, at room temperature<br>- 4 cups all-purpose flour<br>- 1 teaspoon baking powder<br>- 1/2 teaspoon salt<br>- 1 cup whole milk<br>- 1 tablespoon vanilla extract<br><br>Instructions:<br>1. Preheat the oven to 325°F. Grease and flour a 10-inch tube pan.<br>2. In a large bowl, beat the butter until creamy, about 2-3 minutes. Gradually add the sugar and continue to beat until light and fluffy, about 5-7 minutes.<br>3. Add the eggs, one at a time, beating well after each addition.<br>4. In a separate bowl, whisk together the flour, baking powder, and salt. Gradually add the dry ingredients to the butter mixture, alternating with the milk, beginning and ending with the dry ingredients. Stir in the vanilla extract.<br>5. Pour the batter into the prepared pan and smooth the top with a spatula. Bake for 1 hour and 20-30 minutes, or until a toothpick inserted into the center of the cake comes out clean.<br>6. Let the cake cool in the pan for 10 minutes, then remove from the pan and let cool completely on a wire rack. Serve the pound cake plain or with your favorite toppings.",
        price:50
    },
    {
        id:7,
        name:'Angel Food Cake',
        images: 'https://handletheheat.com/wp-content/uploads/2022/06/angel-food-cake-recipe-SQUARE.jpg',
        image1:"https://www.wilton.com/dw/image/v2/AAWA_PRD/on/demandware.static/-/Sites-wilton-project-master/default/dw460a34a9/images/project/WLRECIP-8643/angel-food-cake-with-berries-and-whipped-cream-recipe.jpg?sw=800&sh=800",
        description:"This is a light, fluffy cake made with egg whites, sugar, and flour. It is often served with fruit or whipped cream.",
        description1: "Ingredients:<br><br>- 1 cup cake flour<br>- 1 1/2 cups granulated sugar, divided<br>- 12 egg whites, at room temperature<br>- 1/4 teaspoon salt<br>- 1 1/2 teaspoons cream of tartar<br>- 1 teaspoon vanilla extract<br><br>Instructions:<br><br>1. Preheat your oven to 350°F (175°C).<br>2. Sift together the cake flour and 1/2 cup of granulated sugar three times. This will ensure a light and fluffy cake.<br>3. In a large bowl, beat the egg whites, salt, and cream of tartar until soft peaks form.<br>4. Gradually add the remaining 1 cup of granulated sugar, one tablespoon at a time, and beat until stiff peaks form.<br>5. Add the vanilla extract and beat for a few seconds to combine.<br>6. Sift the flour mixture over the egg white mixture, about 1/4 cup at a time, and gently fold in with a spatula until the flour is incorporated.<br>7. Spoon the batter into an ungreased 10-inch tube pan and smooth the top.<br>8. Bake for 35-40 minutes, or until the top of the cake springs back when lightly touched.<br>9. Remove the cake from the oven and immediately invert the pan onto a wire rack. Let the cake cool completely upside down in the pan.<br>10. Once the cake is cool, run a knife around the edges of the pan to loosen the cake, and then remove it from the pan.<br>11. Serve the cake with fresh fruit, whipped cream, or your favorite toppings.",
        price:36
        
    },
    {
        id:8,
        name:'Fruitcake',
        images: 'https://media.istockphoto.com/id/610542488/photo/easter-fruitcake-on-the-stone-background.jpg?s=612x612&w=0&k=20&c=qDvowcpZ18-DChVyp_fAxO6dkbpbF1BFXvs08LEt6DQ=',
        image: 'https://c4.wallpaperflare.com/wallpaper/893/378/483/dessert-sweet-laying-cream-wallpaper-preview.jpg',

        description:"A dense cake filled with dried fruit and nuts. It is often made with alcohol and can be aged for several months.",
        description1: "Fruitcake Recipe:<br><br>Ingredients:<br>- 1 cup unsalted butter<br>- 1 cup brown sugar<br>- 4 eggs<br>- 1/4 cup orange juice<br>- 2 cups all-purpose flour<br>- 1/2 teaspoon baking powder<br>- 1/2 teaspoon baking soda<br>- 1/2 teaspoon salt<br>- 1 teaspoon ground cinnamon<br>- 1/2 teaspoon ground nutmeg<br>- 1/4 teaspoon ground allspice<br>- 1/4 teaspoon ground cloves<br>- 1 cup candied cherries<br>- 1 cup chopped dried apricots<br>- 1 cup raisins<br>- 1 cup currants<br>- 1 cup chopped pecans<br>- 1/2 cup brandy or rum<br><br>Instructions:<br>1. Preheat the oven to 325°F. Grease and flour a 10-inch bundt pan.<br>2. In a large bowl, cream together the butter and brown sugar until light and fluffy. Beat in the eggs, one at a time, and then stir in the orange juice.<br>3. In a separate bowl, whisk together the flour, baking powder, baking soda, salt, cinnamon, nutmeg, allspice, and cloves.<br>4. Gradually add the dry ingredients to the wet ingredients, stirring until just combined.<br>5. Fold in the cherries, apricots, raisins, currants, and pecans.<br>6. Pour the batter into the prepared pan and smooth the top with a spatula.<br>7. Bake for 1 hour and 20 minutes or until a toothpick inserted into the center of the cake comes out clean.<br>8. Let the cake cool in the pan for 10 minutes, then turn it out onto a wire rack to cool completely.<br>9. Once the cake has cooled, brush the top with brandy or rum.<br>10. Wrap the cake tightly in plastic wrap and store it in the refrigerator. The cake will keep for up to 3 months, and the longer it ages, the better the flavor will be.",
        price:36
    },
    {
        id:9,
        name:'Tiramisu Cake',
        images: 'https://media.istockphoto.com/id/1061450296/photo/portion-of-tiramisu-dessert.jpg?s=612x612&w=0&k=20&c=JyWeXtC9k7a4pGPhJxmedRFiR2WWt6-iYmDFdP6CScc=',
        image1:"https://www.alsothecrumbsplease.com/wp-content/uploads/2018/05/Tiramisu-Cake-25.jpg",
        description:"An Italian dessert made with layers of ladyfingers soaked in espresso and mascarpone cheese, often dusted with cocoa powder.  ",
        description1: "Ingredients:<br><br>- 1 1/4 cups all-purpose flour<br>- 1 1/2 teaspoons baking powder<br>- 1/4 teaspoon salt<br>- 3 large eggs<br>- 3/4 cup granulated sugar<br>- 1/2 cup vegetable oil<br>- 1 teaspoon vanilla extract<br>- 1/2 cup whole milk<br>- 1/4 cup brewed espresso or strong coffee<br>- 1/4 cup rum<br>- 8 ounces mascarpone cheese<br>- 1/2 cup powdered sugar<br>- 1 cup heavy cream<br>- Cocoa powder for dusting<br><br>Instructions:<br><br>1. Preheat the oven to 350°F (180°C). Grease and flour a 9-inch (23 cm) cake pan.<br><br>2. In a medium bowl, whisk together the flour, baking powder, and salt.<br><br>3. In a separate large bowl, beat the eggs and granulated sugar with an electric mixer until light and fluffy, about 3-4 minutes.<br><br>4. Gradually mix in the vegetable oil and vanilla extract.<br><br>5. Add the dry ingredients to the wet mixture in two batches, alternating with the whole milk and mixing until just combined.<br><br>6. Pour the batter into the prepared cake pan and bake for 25-30 minutes, or until a toothpick inserted into the center of the cake comes out clean.<br><br>7. While the cake is baking, combine the brewed espresso or strong coffee and rum in a small bowl.<br><br>8. In a separate large bowl, whisk together the mascarpone cheese and powdered sugar until smooth.<br><br>9. In another large bowl, beat the heavy cream with an electric mixer until soft peaks form.<br><br>10. Fold the whipped cream into the mascarpone mixture until smooth and creamy.<br><br>11. Once the cake has cooled, slice it in half horizontally to create two layers.<br><br>12. Brush the espresso and rum mixture over both sides of each cake layer.<br><br>13. Spread a layer of the mascarpone cream on top of one cake layer, then place the other cake layer on top.<br><br>14. Spread the remaining mascarpone cream over the top and sides of the cake.<br><br>15. Dust the top of the cake with cocoa powder and refrigerate for at least 2 hours before serving.<br><br>Enjoy your delicious Tiramisu Cake!",
        price:51
    },
    {
        id:10,
        name:'marble cake',
        images: 'https://media.istockphoto.com/id/1210494353/photo/bread-loaf-with-cocoa.jpg?s=612x612&w=0&k=20&c=mQ9zQLtSO_ecFhlM_cpFNZ-UOWas4FY6t501DCh0Df8=',
        image1:"https://t3.ftcdn.net/jpg/03/21/02/72/360_F_321027238_u38SodAyFaybXk8YzbsKiTQnsDvLVVwG.jpg",
        description:"made by combining two different types of cake batters together to create a swirled or marbled effect. Typically, a vanilla and chocolate cake batter are used for this purpose, with the two batters being swirled together in the cake pan before baking. ",
        description1:"Ingredients:<br><br>2 cups all-purpose flour<br>2 teaspoons baking powder<br>1/2 teaspoon salt<br>1/2 cup unsalted butter, softened<br>1 cup granulated sugar<br>2 large eggs<br>1 teaspoon vanilla extract<br>3/4 cup milk<br>2 tablespoons unsweetened cocoa powder<br><br>Instructions:<br><br>Preheat your oven to 350°F (175°C). Grease a 9-inch cake pan with cooking spray or butter.<br>In a medium bowl, whisk together the flour, baking powder, and salt.<br>In a separate large bowl, cream the butter and sugar until light and fluffy using a hand mixer or stand mixer.<br>Beat in the eggs one at a time, then stir in the vanilla extract.<br>Gradually add the dry ingredients to the wet mixture, alternating with the milk, and mix until just combined.<br>Scoop out 1/3 of the batter and place it into a separate bowl. Mix in the cocoa powder until well combined.<br>Pour half of the vanilla batter into the greased cake pan, followed by half of the chocolate batter. Use a butter knife to swirl the two batters together.<br>Repeat with the remaining vanilla and chocolate batters.<br>Bake the cake for 40-45 minutes, or until a toothpick inserted into the center comes out clean.<br>Allow the cake to cool for 10-15 minutes in the pan before removing it and placing it onto a wire rack to cool completely.<br>Slice and serve!",
        price:51
        
    },
    {
        id:11,
        name:'Black Forest ',
        images: 'https://media.istockphoto.com/id/1214305490/photo/blackforest-cake.jpg?b=1&s=170667a&w=0&k=20&c=4drprf3ExjpnbIEk_ORWDPrMtj6BdEUmmic65sQbPGQ=',
        image1:"https://www.sainsburysmagazine.co.uk/media/4577/download/black-forest-gateau-560.jpg?v=1",
        description:"A rich, chocolate cake layered with cherries and whipped cream. It is often decorated with chocolate shavings.",
        description1: "Ingredients:<br><br>For the cake:<br>1 cup all-purpose flour<br>1 cup granulated sugar<br>1/3 cup unsweetened cocoa powder<br>1 teaspoon baking powder<br>1/2 teaspoon baking soda<br>1/2 teaspoon salt<br>1/2 cup vegetable oil<br>2 large eggs<br>1 teaspoon vanilla extract<br>1/2 cup hot water<br><br>For the filling and topping:<br>2 cups heavy cream, divided<br>1/4 cup powdered sugar<br>1 teaspoon vanilla extract<br>1 (21-ounce) can cherry pie filling<br>Chocolate shavings, for decoration<br><br>Instructions:<br><br>1. Preheat your oven to 350°F (175°C). Grease two 9-inch cake pans with cooking spray or butter.<br>2. In a large mixing bowl, whisk together the flour, sugar, cocoa powder, baking powder, baking soda, and salt.<br>3. Add the vegetable oil, eggs, and vanilla extract to the dry ingredients and beat with an electric mixer on medium speed until well combined.<br>4. Gradually pour in the hot water while beating on low speed. Mix until just combined.<br>5. Divide the batter evenly between the two prepared cake pans and smooth the tops with a spatula.<br>6. Bake the cakes for 25-30 minutes, or until a toothpick inserted into the center of the cake comes out clean.<br>7. Let the cakes cool in the pans for 10 minutes, then remove them from the pans and cool completely on a wire rack.<br>8. To make the filling, beat 1 1/2 cups of heavy cream, powdered sugar, and vanilla extract in a large mixing bowl until stiff peaks form.<br>9. To assemble the cake, place one cake layer on a serving plate and spread a layer of cherry pie filling over the top. Then, spread a thick layer of whipped cream over the cherries. Repeat with the second cake layer, cherry pie filling, and whipped cream.<br>10. Use a spatula to smooth out the whipped cream on the top and sides of the cake.<br>11. Whip the remaining 1/2 cup of heavy cream until soft peaks form. Pipe rosettes of whipped cream around the top edge of the cake.<br>12. Decorate the top of the cake with chocolate shavings.<br>13. Chill the cake in the refrigerator for at least 2 hours before serving.",
        price:40

    },
    {
        id:12,
        name:'Funfetti cake',
        images: 'https://thumbs.dreamstime.com/b/birthday-party-cake-sprinkles-white-buttercream-confetti-birthday-cake-slice-colorful-sprinkles-over-gray-111589563.jpg',
        image1:"https://therecipecritic.com/wp-content/uploads/2022/01/funfetticake-751x1000.jpg",
        description:"A colorful and festive cake made with rainbow sprinkles mixed into the batter, often topped with vanilla frosting and more sprinkles.",
        description1: "this Funfetti cake recipe is perfect for birthdays or any celebration! Made with simple ingredients like flour, sugar, and butter, and filled with colorful rainbow sprinkles, this cake is sure to be a hit with both kids and adults alike. Here's how to make it:<br><br>Ingredients:<br>- 1 1/2 cups all-purpose flour<br>- 1 cup granulated sugar<br>- 2 teaspoons baking powder<br>- 1/2 teaspoon salt<br>- 1/2 cup unsalted butter, softened<br>- 2 large eggs<br>- 1/2 cup whole milk<br>- 2 teaspoons vanilla extract<br>- 1/2 cup rainbow sprinkles<br><br>For the frosting:<br>- 1/2 cup unsalted butter, softened<br>- 2 cups powdered sugar<br>- 2 tablespoons whole milk<br>- 1 teaspoon vanilla extract<br>- Additional rainbow sprinkles for decorating<br><br>Instructions:<br>1. Preheat your oven to 350°F (175°C). Grease an 8-inch square baking pan with cooking spray or butter.<br>2. In a large mixing bowl, whisk together the flour, sugar, baking powder, and salt.<br>3. Add the butter, eggs, milk, and vanilla extract to the dry ingredients and beat with an electric mixer on medium speed until well combined.<br>4. Fold in the rainbow sprinkles with a spatula.<br>5. Pour the batter into the prepared pan and smooth the top with a spatula.<br>6. Bake the cake for 25-30 minutes, or until a toothpick inserted into the center of the cake comes out clean.<br>7. Let the cake cool in the pan for 10 minutes, then remove it from the pan and cool completely on a wire rack.<br>8. To make the frosting, beat the butter with an electric mixer on medium speed until smooth.<br>9. Gradually add the powdered sugar, milk, and vanilla extract, beating on low speed until well combined.<br>10. Increase the speed to high and beat until the frosting is light and fluffy.<br>11. Frost the top and sides of the cooled cake with the frosting.<br>12. Sprinkle additional rainbow sprinkles over the top of the cake for decoration.<br>13. Serve and enjoy your Funfetti cake!",
        price:40

        
    },
    
    

]